# Generated by Django 4.0.4 on 2022-05-13 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='role',
            name='capable_mentors',
            field=models.ManyToManyField(blank=True, null=True, related_name='capabilities', to=settings.AUTH_USER_MODEL),
        ),
    ]
